### ISSUE TITLE
not having java

### ISSUE THREAD

**Issue by serbanghita** [bogdananton/Selenium-Setup#8]
The execution should be stopped, or at least we should try to fetch it on unix

![java-error-phpunit-env](https://cloud.githubusercontent.com/assets/1106849/11255525/668dd42c-8e4f-11e5-8c61-5de05e8b55f8.PNG)

**Comment by serbanghita** [comment]
the `check` task should include a fast checkup and display all errors and stop the build

**Comment by bogdananton** [comment]
fixed by cc5ef0b4b0b1979a943726ffa86b8825ebba09d1
